apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector: 
     app: myjenkins
     version: 2.60.3:1
   template:
     metadata:
       labels:
          app: myjenkins
          version: 2.60.3:1
     spec:
        containers:
        - name: myjenkins-container   
          image: jenkins:2.60.3:1
          ports:
          - containerPort: 8080  